cell_states: 3
cell_type: 'uint8'

cell_symbols:
  empty: 0
  tree:  1
  fire:  2

grid_shape:
  n_row: 5
  n_col: 5

ca_params:
  p_fire: 0.033
  p_tree: 0.333

# The Modifier's effects:
# Exchanging a FIRE cell to EMPTY.
effects:
  2: 0

actions:
  up_left:       1
  up_center:     2
  up_right:      3
  middle_left:   4
  middle_center: 5
  middle_right:  6
  down_left:     7
  down_center:   8
  down_right:    9

action_type: 'uint8'

# Steps that the Cellular Automaton remains idle.
max_freeze: 2

rewards:
  per_empty: 0.0
  per_tree: 1.0
  per_fire: -1.0

# Cellular Automata rendering options.
cell_colors:
  empty: '#F5A6AB' # Pink/Soft Red
  tree:  '#62A873' # Pine Green
  fire:  '#A85156' # Wine Red

plot_title: 'Forest Fire Environment'
plot_font: 'Lato' 
