cell_states: 3
cell_type: 'uint8'

cell_symbols:
  empty: 0
  tree:  1
  fire:  2

grid_shape:
  n_row: 5
  n_col: 5

ca_params:
  p_fire: 0.033
  p_tree: 0.333

# Modifier's effects
# Change FIRE to EMPTY
effects:
  fire: 'empty'

n_actions: 9
action_type: 'uint8'

actions:
  up_left:    1
  up:         2
  up_right:   3
  left:       4
  not_move:   5
  right:      6
  down_left:  7
  down:       8
  down_right: 9

# Steps that the Cellular Automaton remains idle.
max_freeze: 2

rewards:
  per_empty: 0.0
  per_tree:  1.0
  per_fire: -1.0

# Cellular Automata rendering options.
cell_colors:
  empty: '#F5A6AB' # Pink/Soft Red
  tree:  '#62A873' # Pine Green
  fire:  '#A85156' # Wine Red

plot_title: 'Forest Fire Environment'
plot_font:  'Lato' 
